#apiVersion: v1
#kind: Service
#metadata:
#  name: flask-service
#spec:
#  type: NodePort
#  selector:
#    app: flask-ci-cd
#  ports:
#  - port: 5000
#    targetPort: 5000
#    nodePort: 30001
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask-ci-cd
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007

